// Nova v1.0 — JS Flow
const traits = [
  "Adaptive","Analytical","Authentic","Balanced","Bold","Calm","Caring","Collaborative","Confident","Consistent",
  "Creative","Curious","Decisive","Determined","Disciplined","Empathetic","Enthusiastic","Focused","Generous","Grounded",
  "Honest","Humble","Imaginative","Independent","Innovative","Intentional","Kind","Learner","Leader","Listener",
  "Mindful","Optimistic","Organized","Passionate","Patient","Persistent","Playful","Pragmatic","Proactive","Resilient",
  "Resourceful","Risk‑taker","Strategic","Supportive","Thoughtful","Thorough","Trustworthy","Visionary","Whole‑hearted","Wise"
];

const $ = q=>document.querySelector(q);
const $$ = q=>document.querySelectorAll(q);

function goto(selector){
  $$(".panel").forEach(p=>p.classList.remove("active"));
  $(selector).classList.add("active");
  $$(".step").forEach(s=>s.classList.remove("active"));
  const stepBtn=[...$$(".step")].find(s=>s.dataset.target===selector);
  if(stepBtn) stepBtn.classList.add("active");
  if(selector==="#summary") renderSummary();
}

$$(".step").forEach(btn=>btn.addEventListener("click",()=>goto(btn.dataset.target)));
$("#toTraits").addEventListener("click",()=>goto("#traits"));
$("#toSummary").addEventListener("click",()=>goto("#summary"));
$("#backToTraits").addEventListener("click",()=>goto("#traits"));
$$("[data-target]").forEach(btn=>btn.addEventListener("click",()=>goto(btn.dataset.target)));

const grid=$("#traitGrid");
function renderTraits(){
  grid.innerHTML="";
  traits.forEach((t,i)=>{
    const id="trait_"+i;
    const wrap=document.createElement("label");
    wrap.className="trait";
    wrap.innerHTML=`<input id="${id}" type="checkbox" value="${t}"/><span>${t}</span>`;
    grid.appendChild(wrap);
  });
}
renderTraits();

$("#clearTraits").addEventListener("click",()=>{
  $$("#traitGrid input[type=checkbox]").forEach(el=>el.checked=false);
});

function selectedTraitList(){return [...$$("#traitGrid input[type=checkbox]")].filter(el=>el.checked).map(el=>el.value);}
function renderSummary(){$("#selectedTraits").textContent=selectedTraitList().join(", ");}

document.getElementById("downloadPDF").addEventListener("click", async()=>{
  const {jsPDF}=window.jspdf;const doc=new jsPDF();
  const name=$("#userName").value||"Nova Explorer";const email=$("#userEmail").value||"";const picks=selectedTraitList();
  doc.setFillColor(17,23,54);doc.rect(0,0,210,40,"F");doc.setTextColor(255,255,255);doc.setFontSize(22);doc.text("NOVA — Trait Report",14,20);
  doc.setFontSize(12);doc.text("Find Your Way",14,28);
  doc.setTextColor(0,0,0);doc.setFontSize(12);let y=50;
  doc.text(`Name: ${name}`,14,y);y+=8;if(email){doc.text(`Email: ${email}`,14,y);y+=8;}
  doc.text("Selected Traits:",14,y);y+=8;let colW=60;let x=14;let col=0;let row=0;
  picks.forEach((t,idx)=>{doc.text("• "+t,x,y+row*8);row++;if(row>=20){row=0;col++;x=14+col*colW;}});
  doc.setFontSize(10);doc.text("© Nova Labs — Generated by Nova",14,285);doc.save("Nova_Trait_Report.pdf");
});

window.addEventListener("load",()=>{const a=document.getElementById("introAudio");if(a){a.volume=0.85;a.play().catch(()=>{});}});
